### ISSUE TITLE
PagedGeometryConfig.h.in in include/ 

### ISSUE THREAD

**Issue by Grokafar** [RigsOfRods/ogre-pagedgeometry#1]
There is "PagedGeometryConfig.h.in"  file in include/  shouldn't be PagedGeometryConfig.h ? That cause a compilation problem in RigsOfRods which can't find  PagedGeometryConfig.h.
That file wasn't in the previous repo, it was called "PagedGeometryConfig.h" not "PagedGeometryConfig.h.in"

**Comment by Hiradur** [comment]
Cmake should generate a PagedGeometryConfig.h from PagedGeometryConfig.h.in. Are you sure it's missing?

**Comment by Grokafar** [comment]
Yes, maybe I make a mistake in the compile command. I use that script to compile : 

```
  [[ -d build ]] && rm -rf build
  mkdir build
  cd build
  cmake .. \
    -DPAGEDGEOMETRY_BUILD_SAMPLES=0 \
    -DCMAKE_INSTALL_PREFIX=/usr
  make
```

Did I miss something ? This script worked with the previous repository.

**Comment by Hiradur** [comment]
`make install` is probably missing

**Comment by Grokafar** [comment]
Your right... That was so stupid... Thank you and sorry for the trouble !

**Comment by Hiradur** [comment]
> Your right... That was so stupid... Thank you and sorry for the trouble !

No problem, the old repo had no install target which is why you didn't need make install.
